export const ROUTES = {
  INTRO: '/intro',
  LANDING: '/',
  AUTH: '/auth',
  HOME: '/home',
  ONBOARDING: '/onboarding',
  JOURNEY: '/journey/:id',
  JOURNEYS: '/journeys',
  JOURNEY_DAY: '/journey/:id/day/:dayNumber',
  SESSION: '/session',
  EMOTION_REFLECTION: '/emotion-reflection',
  CALENDAR: '/calendar',
  HISTORY: '/history',
  SETTINGS: '/settings',
  HOW_IT_WORKS: '/how-it-works',
} as const;
